In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np
import pandas as pd
import requests
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [3]:
yearlyInflation=pd.read_csv('inflationWorldBank_yearly_uncleaned.csv')
yearlyInflation
usefulYearlyInflation=yearlyInflation[['Country Name','2015', '2016', '2017', '2018', '2019', '2020']]
# Here we upload yearly inflation data from the World Bank, and then only include columns in the data that countain the name of the country, as well as the years since the Bitcoin data begins.

In [5]:
ALL_usefulYearlyInflation = usefulYearlyInflation[usefulYearlyInflation['Country Name'].str.contains('Switzerland|India|Nigeria|Peru|Philippines|Turkey|Vietnam|United States|China|Japan|Germany')]
bestALL_usefulYearlyInflation = ALL_usefulYearlyInflation.set_index('Country Name').T
bestALL_usefulYearlyInflation.index.name = 'Year'
bestALL_usefulYearlyInflation
# From the previous dataframe, we keep only observations that consist of the countries that are part of the list that have the highest percentage of their citizens owning cryptocurrencies.
# The '|' operater represents 'or' separating the possible strings, hence why this is used.
# Setting the country as the index and then tranposing puts each column as a separate country.
# We then label the index 'Year' as the index will need a name in order to manipulate in Vega.

Country Name  Switzerland     China  ...  United States   Vietnam
Year                                 ...
2015            -1.143909  1.437024  ...       0.118627  0.631201
2016            -0.434619  2.000002  ...       1.261583  2.668248
2017             0.533788  1.593136  ...       2.130110  3.520257
2018             0.936335  2.074790  ...       2.442583  3.539628
2019             0.362886  2.899234  ...       1.812210  2.795824
2020            -0.725875  2.419422  ...       1.233584  3.220934

[6 rows x 13 columns]

In [ ]:
bestALL_usefulYearlyInflation.to_csv('inflation_ALLcountries.csv')
# This is then exported as a CSV file that I upload to my GitHub website.
# Below I do exactly the same but with yearly unemployment rates (from the same dataset).

In [ ]:
yearlyUnemployment=pd.read_csv('unemploymentWorldBank_yearly_uncleaned.csv')
yearlyUnemployment
usefulYearlyUnemployment=yearlyUnemployment[['Country Name','2015', '2016', '2017', '2018', '2019', '2020']]

In [ ]:
ALL_usefulYearlyUnemployment = usefulYearlyUnemployment[usefulYearlyUnemployment['Country Name'].str.contains('Switzerland|India|Nigeria|Peru|Philippines|Turkey|Vietnam|United States|China|Japan|Germany').T]
bestALL_usefulYearlyUnemployment = ALL_usefulYearlyUnemployment.set_index('Country Name').T
bestALL_usefulYearlyUnemployment.index.name = 'Year'
bestALL_usefulYearlyUnemployment

Country Name  Switzerland  China  Germany  ...  Turkey  United States  Vietnam
Year                                       ...
2015                 4.80    4.6     4.62  ...   10.24           5.28     1.85
2016                 4.92    4.5     4.12  ...   10.84           4.87     1.85
2017                 4.80    4.4     3.75  ...   10.82           4.36     1.87
2018                 4.71    4.3     3.38  ...   10.89           3.90     1.16
2019                 4.39    4.6     3.14  ...   13.67           3.67     2.04
2020                 4.94    5.0     4.31  ...   13.92           8.31     2.27

[6 rows x 13 columns]

In [ ]:
bestALL_usefulYearlyUnemployment.to_csv('unemployment_ALLcountries.csv')